version: '3.4'

services:
  todo:
    image: joel/todo:latest
    build:
      context: .
      dockerfile: ToDo/Dockerfile
    container_name: todo
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=ToDoDb;
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ToDoDb
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgsql_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=aa@bb.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - 7001:80
    depends_on:
      - postgres

volumes:
  pgsql_data: